### ISSUE TITLE
bug in mxfb-accessories

### ISSUE THREAD

**Issue by ghost** [AdrianTM/mx-tools#3]
it's about this
https://github.com/MX-Linux/mxfb-accessories

I can't open an issue there, so i'm dumping it here and i don't see instructions where to go.

`apt/apt.conf.d/00mxfb-menu-geneator` expects `/usr/share/applications/antix` to exist, i added the repo in debian and just installed mx-fluxbox . So the folder doesn't exist and that blocks apt from installing anything.

```
E: Problem executing scripts DPkg::Pre-Invoke 'if [ -x /usr/bin/mxfb-menu-generator ]; then /usr/bin/stat -c %Y /usr/share/applications /usr/share/applications/antix 2>/dev/null > /tmp/dpkg-pre-invoke-timestamp; fi'
E: Sub-process returned an error code
```

Edit: https://github.com/MX-Linux/mxfb-accessories/issues/102

**Comment by AdrianTM** [comment]
I enabled "issues" in mxfb-accessories, can you please post this there? (so you can follow it)
